import { Router } from 'express';
import adminRouter from './admin.js';
import analyzeRouter from './analyze.js';
import authRouter from './auth.js';
import brandRegistryRouter from './brand-registry.js';
import cdnRouter from './cdn.js';
import configRouter from './config.js';
import connectionsRouter from './connections.js';
import diagRouter from './diag.js';
import dropboxRouter from './dropbox.js';
import draftsRouter from './drafts.js';
import ebayRouter from './ebay.js';
import identityRouter from './identity.js';
import imagesRouter from './images.js';
import imgRouter from './img.js';
import ingestRouter from './ingest.js';
import listingsRouter from './listings.js';
import pricingRouter from './pricing.js';
import promotionsRouter from './promotions.js';
import settingsRouter from './settings.js';
import smartdraftsRouter from './smartdrafts.js';
import statusRouter from './status.js';
import taxonomyRouter from './taxonomy.js';

export const router = Router();

router.use('/admin', adminRouter);
router.use('/brand-registry', brandRegistryRouter);
router.use('/analyze', analyzeRouter);
router.use('/auth', authRouter);
router.use('/cdn', cdnRouter);
router.use('/config', configRouter);
router.use('/connections', connectionsRouter);
router.use('/diag', diagRouter);
router.use('/dropbox', dropboxRouter);
router.use('/drafts', draftsRouter);
router.use('/ebay', ebayRouter);
router.use('/images', imagesRouter);
router.use('/img', imgRouter);
router.use('/ingest', ingestRouter);
router.use('/listings', listingsRouter);
router.use('/me', identityRouter);
router.use('/pricing', pricingRouter);
router.use('/promotions', promotionsRouter);
router.use('/settings', settingsRouter);
router.use('/smartdrafts', smartdraftsRouter);
router.use('/status', statusRouter);
router.use('/taxonomy', taxonomyRouter);
